---
- hosts: "{{ hosts_var | default('ceph-nodes') }}"
  tasks:
    - name: add ceph_admin SSH public key to authorized_keys
      blockinfile:
        block: "{{ lookup('file', '../secrets/ceph_admin_id_rsa.pub') }}"
        dest: ~/.ssh/authorized_keys
        create: yes
        mode: 0600
